config/routes.rb
Wischlist::Application.routes.draw do
  resources :list_items

  resources :lists

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"
  
  resources :products do 
    get :who_bought, on: :member
  end

  root to: 'store#index', as: 'store'
  
  match '/search' => 'search#search'
  

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :list_items, dependent: :destroy
  
  def add_list_item(web_id)
    
    current_item = list_items.find_by_web_id(web_id)
    
    if current_item
      list_items.each do | item |
        
        if item.web_id == web_id[0]
          item.quantity += 1
          item.save
          return item
        end
      end
    else
      is = ItemLookup.new( 'ASIN', { 'ItemId' => web_id[0] } )
      is.response_group = ResponseGroup.new( 'Small' )
      
      req = Request.new
      resp = req.search( is )
      
      items = resp.item_lookup_response[0].items[0].item
      
      attribs = items[0].item_attributes[0]

      title = String.try_convert(attribs.title)
      
      ### Picture
      is = ItemLookup.new( 'ASIN', { 'ItemId' => web_id[0] } )
      is.response_group = ResponseGroup.new( 'Images' )
      
      req = Request.new
      resp = req.search( is )
      
      items = resp.item_lookup_response[0].items[0].item
      
      image_url = "http://g-ecx.images-amazon.com/images/G/03/x-site/icons/no-img-sm._AA75_.gif"
      url = String.try_convert(items[0].small_image)
      if url
        startIndex = url.index("http")
        endIndex = url.index("height")
      
        image_url = url[startIndex..endIndex-2]
      end
      
      # build method is inherited from ActiveRecord:Base and create in this case
      # a new list_item with given product_id. :web_id => web_id is a 
      # short form for a array entry
      current_item = list_items.build(:web_id => web_id[0], :title => title, :picture_url => image_url)
    end
    current_item
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div class="list_title">Your list</div>
<br />
<table width="100%">
  <!-- will past partial code of file _line_item.html.erb for each element at line_items -->
  <%= render :partial => list.list_items %>

</table>

<!-- i am not quite shure what this line of code does. have to do after get over this-->
<%= button_to "Empty list", list, :method => "delete", :confirm => "Are you shure?" %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing lists</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= link_to 'Show', list %></td>
    <td><%= link_to 'Edit', edit_list_path(list) %></td>
    <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<%= render @list %>