config/routes.rb
Wischlist::Application.routes.draw do
  resources :list_items

  resources :lists

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"
  
  resources :products do 
    get :who_bought, on: :member
  end

  root to: 'store#index', as: 'store'
  
  match '/search' => 'search#search'
  

end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  attr_accessible :web_id, :picture_url, :title
  
  belongs_to :list
  
  def get_title
    
    if @listItem.title
      
      puts "############ title known"
      return @listItem.title
    else

      puts "title not known"
      is = ItemLookup.new( 'ASIN', { 'ItemId' => web_id,
               'MerchantId' => 'Amazon' } )
      is.response_group = ResponseGroup.new( 'Small' )
      
      req = Request.new
      resp = req.search( is )
      
      items = resp.item_lookup_response[0].items[0].item
      
      items.each do |item|
        
        attribs = item.item_attributes[0]
        @listItem.title = attribs.title
        
        return @listItem.title
      end     
    end
  end
  
  def get_picture
    
    if @listItem.picture_url
      puts "##################picture url known"
      
      return @listItem.picture_url
    else
      puts "##################picture url not known"
      puts self.picture_url
    
      is = ItemLookup.new( 'ASIN', { 'ItemId' => web_id } )
      is.response_group = ResponseGroup.new( 'Medium' )
      
      req = Request.new
      resp = req.search( is )
      
      items = resp.item_lookup_response[0].items[0].item
      
      items.each do |item|
        
        attribs = item.item_attributes[0]
        url = String.try_convert(item.small_image)
        if url
          
          startIndex = url.index("http")
          endIndex = url.index("height")
        
          @listItem.picture_url = url[startIndex..endIndex-2] 
        
          return @listItem.picture_url 
        else
          
          @listItem.picture_url = "http://g-ecx.images-amazon.com/images/G/03/x-site/icons/no-img-sm._AA75_.gif"
          return @listItem.picture_url
        end
      end
    end
  end
end
  

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  # GET /list_items
  # GET /list_items.json
  def index
    @list_items = ListItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @list_items }
    end
  end

  # GET /list_items/1
  # GET /list_items/1.json
  def show
    @list_item = ListItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list_item }
    end
  end

  # GET /list_items/new
  # GET /list_items/new.json
  def new
    @list_item = ListItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list_item }
    end
  end

  # GET /list_items/1/edit
  def edit
    @list_item = ListItem.find(params[:id])
  end

  # POST /list_items
  # POST /list_items.json
  def create
    
    # current_list is a method in application_controllers
    @list = current_list  
    @list_item = @list.add_list_item(params[:web_id])

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to store_url }
        # rails assume there is a file called create.js.erb
        format.js
        format.json { render json: @list_item, status: :created, location: @list_item }
      else
        format.html { render action: "new" }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /list_items/1
  # PUT /list_items/1.json
  def update
    @list_item = ListItem.find(params[:id])

    respond_to do |format|
      if @list_item.update_attributes(params[:list_item])
        format.html { redirect_to @list_item, notice: 'List item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.json
  def destroy
    @list_item = ListItem.find(params[:id])
    @list_item.destroy

    respond_to do |format|
      format.html { redirect_to list_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/views/list_items/_form.html.erb
<%= form_for(@list_item) do |f| %>
  <% if @list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_item.errors.count, "error") %> prohibited this list_item from being saved:</h2>

      <ul>
      <% @list_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_items/_list_item.html.erb
<tr>
  <td><%= list_item.title %></td>
</tr>
<tr>
  <td><img src="<%= list_item.picture_url %>"></img></td>
</tr>
<tr>
  <td><%= list_item.quantity %>&times;</td>
</tr>
<tr>
  <td height="10px"></td>
</tr>

app/views/list_items/create.js.erb
$("#notice").hide();

$('#right').html("<%=j render @list %>");

app/views/list_items/edit.html.erb
<h1>Editing list_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_item %> |
<%= link_to 'Back', list_items_path %>

app/views/list_items/index.html.erb
<h1>Listing list_items</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @list_items.each do |list_item| %>
  <tr>
    <td><%= link_to 'Show', list_item %></td>
    <td><%= link_to 'Edit', edit_list_item_path(list_item) %></td>
    <td><%= link_to 'Destroy', list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List item', new_list_item_path %>

app/views/list_items/new.html.erb
<h1>New list_item</h1>

<%= render 'form' %>

<%= link_to 'Back', list_items_path %>

app/views/list_items/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_list_item_path(@list_item) %> |
<%= link_to 'Back', list_items_path %>